#!/bin/bash

# The `command` hook script will replace the default implementation of running
# the build command.

# Note that as the script is sourced not run directly, the shebang line will be ignored
# See https://buildkite.com/docs/agent/v3/hooks#creating-hook-scripts

set -e

echo "+++ This is the repo command hook"
echo ""
echo "I can use this to modify how the command is going to be executed"
echo ""
echo "The command to be executed is /'$BUILDKITE_COMMAND/'"
echo ""
eval $BUILDKITE_COMMAND
